# Introduction to NUMPY

In [ ]:
# Numpy - Numerical Python
# library needed "numpy"
# "np" is the usual alias for numpy
# in numpy everything is considered as array, can't understand anything else.
# "ndarray" - n-dimensional array
# "np.min()","np.max()","np.mean()","np.median()","np.std()","np.var()"
# "np.zeros(())"
# "np.full([row,col],value)"
# "np.array_equal()"
# "np.logical_or" etc..
# "np.savetext("file_name.csv")" - save file
# "variable_name.flatten()" - back to array form from list

In [2]:
#create tuple and converting into array
#array - [1 2 3]
#list - [1,2,3]

import numpy as np
tuple_1 = (1,2,3)
print("tuple_1:" ,type(tuple_1))
tuple_11 = np.array(tuple_1)
print("tuple_11:",tuple_11)
print(type(tuple_11))

tuple_1: <class 'tuple'>
tuple_11: [1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#list into array

import numpy as np
list_1 = [1,2,3,4]
list_11 = np.array(list_1)
print(list_11)

In [ ]:
#dict into array

import numpy as np
dict_1 = {"Name":"Vidhu","Weight":40}
dict_11 = np.array(dict_1)
print(dict_11)
print(type(dict_11))

In [ ]:
#displaying shape of array

import numpy as np
list_1 = [1,2,3,4]
list_11 = np.array(list_1)
print(list_11)

print("Shape: ",list_11.shape)

In [ ]:
#output of shape here is (1 row, 4 elements) -> ndmin = 2

list_111 = np.array(list_11,ndmin = 2)
print(list_111.shape)

In [ ]:
#output for ndmin = 3 is (1 matrix, 1 row, 4 elements)

list_111 = np.array(list_11,ndmin = 3)
print(list_111.shape)

In [ ]:
#typecasting float into int

list_1 = [1.56,2.66,3.88,4.98]
list_11 = np.array(list_1,dtype=int)
print(list_11)

In [ ]:
#Task - create list with elements in integer, convert into array.

import numpy as npy
list_2 = [1,2,3,4,5,6]
list_21 = npy.array(list_2,ndmin = 2,dtype=float)
print("DataType:",type(list_21))
print("Value: ",list_21)
print("Shape: ",list_21.shape)

In [18]:
#array-scalar type

import numpy as np
list_2 = [1234567891,21,31,41,51,61]
list_21 = np.array(list_2,np.int8)
print(list_21)


[-45  21  31  41  51  61]


In [ ]:
#8-bit -- 1 byte, 16-bit -- 2 bytes, 32-bit -- 4 bytes, 64-bit -- 8 bytes
#int8, int16, int32, int64 -> "i1","i2","i4" etc..
import numpy as np
dt = np.dtype("i4")
print(dt)

list_3 = [1,2]
list_31 = np.array(list_3,dtype = dt)
print(list_31)
print(list_31.nbytes)


In [ ]:
a = [[1,2],[1,4]]
b = np.array(a)
c = b.reshape(2,2) #2 rows and 2 columns
print("c:",c)

In [ ]:
#3 rows and 3 columns
a1 = [[1,2,3],[4,5,6],[7,8,9]]
b1 = np.array(a1,ndmin = 3)
c1 = b1.reshape(3,3)
print(c1)
print(b1.shape)

In [ ]:
#2 rows and 3 columns
a1 = [[1,2,3],[4,5,6]]
b1 = np.array(a1,ndmin = 3)
c1 = b1.reshape(2,3)
print(c1)
print(b1.shape)

In [3]:
#3 rows and 2 columns
a1 = [1,2,3,4,5,6]
b1 = np.array(a1,ndmin = 1)
c1 = b1.reshape(3,2)
print(c1)
print(type(c1))
print(b1.shape)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
(6,)


In [4]:
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
matrix_1 = np.array(matrix,ndmin = 3)
print(matrix_1.shape)
matrix_2 = matrix_1.reshape(6,2)
print(matrix_2)
print(matrix_1.shape)

(1, 3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(1, 3, 4)


In [5]:
#creating a seq in numpy
#"np.arange" is the keyword
#"ndim" gives the dimension
#if you do not know the values
seq = np.arange(11) #default takes value from 0
print(seq)
print(type(seq))
print(seq.shape)
print(seq.size)
print(seq.itemsize)
print(seq.nbytes)

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(11,)
11
4
44


In [ ]:
seq_1 = np.arange(5,26)
print(seq_1)
seq_2 = np.arange(0,15,2)
print(seq_2)

In [8]:
#linespace prints some random numbers given in a range - (endpoint parameter = True -> accepts the end value) => 
#default 'endpoint'is true
#"linspace"
#"num" is used to get the number of random values.

line = np.linspace(5,10, num = 3, dtype = int)
print(line)
print(np.linspace(0,6, num = 4, endpoint = False))

[ 5  7 10]
[0.  1.5 3.  4.5]


In [9]:
import numpy as np
list_1 = [0,32,50,97,99,24]
list_11 = np.array(list_1)
print((list_11 * (9/5)) + 32)


# def f1():
#     f = (list_11 * (9/5)) + 32
#     print(f)
# f1()

[ 32.   89.6 122.  206.6 210.2  75.2]


In [ ]:
#converting celcius into farenheit using numpy + lambda
import numpy as np
list_1 = [0,32,50,97,99,24]
list_11 = np.array(list_1)
list_f = lambda x : ((x * (9/5)) + 32)
print(list_f(list_11))

In [ ]:
seq_1 = np.arange(1,25)
seq_2 = seq_1.reshape(2,12)
print(seq_2)

In [ ]:
seq_1 = np.arange(24)
seq_2 = seq_1.reshape(2,12)
print(seq_2)

In [ ]:
seq_1 = np.arange(1,25)
seq_2 = seq_1.reshape(2,6,2) #2 matrix of 4 rows and 3 columns
print(seq_2[0])
print("\n")
print(seq_2[1].reshape(2,6))
#print(seq_2)

In [ ]:
A = np.arange(1,17)
A1 = A.reshape(4,4)
print(A1)
B = np.ones((4,4),dtype=int) #double brackets for "np.ones"
print(B)
print("Sum:\n",A1+B)

In [ ]:
# -"random" - keyword.
# -"random" needs numpy.
# -cannot give/specify particular numbers.
# -can give n number of matrixes.
# -all matrix are of same size.
# -"np.random.random((no. of matrix,row,column))"
# -"np.random.randint(start,end,no. of random numbers to be displayed)"

import numpy as np
rand = np.random.random((2,5,5)) #double brackets #no. of matrix,rows,columns
print(rand)

In [ ]:
#randint for specific integer range
z = np.random.randint(5,50,4) #start,end,no. of random values to be displayed
print(z)
print(z.reshape(2,2))

In [ ]:
x = np.arange(1,17)
x = x.reshape(4,4)
y = np.random.random((4,4))
print("Sum:\n",x+y)
z1 = np.add(x,y)
print(z1)

In [ ]:
x = np.arange(1,5)
x1 = x.reshape(2,2)

y = np.arange(5,9)
y1 = y.reshape(2,2)

z = np.dot(x1,y1)
print(z)

In [ ]:
a = 10
b = 5
c = np.divmod(a,b)
print(c)

In [ ]:
listt = [1,2,3,4,5,6,7,8,9]
print(np.mean(listt))
print(np.std(listt))
print(np.var(listt))
print(np.median(listt))
print(np.min(listt))
print(np.max(listt))
print(np.sum(listt))

In [12]:
a = np.arange(1,7)
b = np.arange(7,13)
# print(b)
a1 = a.reshape(3,2)
b1 = b.reshape(2,3)
# print(a1)
# print(b1)
z = np.matmul(a1,b1) #matrix multiplication
z1 = np.dot(a1,b1)
#z = a1 * b1
print(z)
print(z1)


[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [14]:

b = np.full([2,3],9) #"np.full([row,col],value)"
print(b)
c = np.empty([3,3],dtype=int)
print(c)


[[9 9 9]
 [9 9 9]]
[[         1          4 1962631520]
 [       651 1962633008        651]
 [1962633264        651          0]]


In [15]:
import numpy as np
dt = np.dtype([("Age",np.int32)]) #tuple inside list
dt_1 = np.array([10,20,30],dtype = dt)
print(dt_1["Age"])


[10 20 30]


In [ ]:
import numpy as np
emp = np.dtype([("Emp ID: ","i4"),("Name: ","S20"),("Department: ","S20"),("Salary: ","f8")])
emp_1 = np.array([(101,"Abc","CS",1000),(102,"Def","Mech",4000),(103,"Ghi","EEE",5000),(104,"Xyz","ECE",9000)],dtype = emp)
print(emp_1["Salary: "])

In [13]:
#multiplication with broadcasting => a * b
import numpy as np
a = np.arange(1,7)
b = np.array([4,5,3])
a1 = a.reshape(2,3)
c = b * a1
print(c)
#print(c.flatten())

[[ 4 10  9]
 [16 25 18]]


In [18]:
a = np.arange(1,9)
b = np.arange(1,5)
a1 = a.reshape(4,2)
b1 = b.reshape(4,1)
c = a1 * b1
print(c)

[[ 1  2]
 [ 6  8]
 [15 18]
 [28 32]]


In [16]:
#hstack - extends and vstack - two lists in one
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Horizontal Stack: ",np.hstack((a,b))) #double brackets
print("Vertical Stack: ",np.vstack((a,b))) #double brackets

Horizontal Stack:  [1 2 3 4 5 6]
Vertical Stack:  [[1 2 3]
 [4 5 6]]


In [ ]:
a = np.arange(1,17)
mat = a.reshape(4,4)
print(mat)

#print(mat[1][1])
#print(mat[::-1])

print(mat[1:3,1:3]) #printing the center matrix.



In [ ]:
a = np.arange(1,17)
mat = a.reshape(4,4)
q1 = mat[0:2,0:2]
q2 = mat[0:2,2:4]
q3 = mat[2:4,0:2]
q4 = mat[2:4,2:4]
print("\n",q1)
print("\n",q2)
print("\n",q3)
print("\n",q4)

In [20]:
#Triangle
for i in range(1,7):
    print("*"*i)

*
**
***
****
*****
******


In [5]:
odd = [1,3,5]
odd.sort()
print(odd)
if(len(odd)%2 != 0):
    x1 = (len(odd)//2) 
else:
    x2 = len(o)/2
    x3 = (len(o)/2 - 1)
    x4 = o[x2]
    x5 = o[x3]
    x6 = (x4 + x5) / 2
print(odd[x1])
#print(odd[x6])

    
#print(11//2) 

[1, 3, 5]
3


In [2]:
7/2

3.5